### ISSUE TITLE
Cannot load data source in Gragana 6.7.1

### ISSUE THREAD

**Issue by ajaywazir** [grafana/opcua-datasource#5]
When adding opc UA datasource, I receive success pop up but the screen shows 

Unexpected token '<' Evaluating http://localhost:8800/public/plugins/grafana-opcua-datasource/module.js Loading plugins/grafana-opcua-datasource/module
Data Source Error

Please let me know how to fix

Ajay

**Comment by srclosson** [comment]
@ajaywazir: Did you ever figure this out? Sorry... it's been like 2 1/2 months

**Comment by ajaywazir** [comment]
Hi 
Sorry. I did not try afterwards

**Comment by wuzhoubr** [comment]
I also meet this issue：Unexpected token '<' Evaluating http://127.0.0.1:8080/public/plugins/grafana-opcua-datasource/module.js Loading plugins/grafana-opcua-datasource/module
how to deal with it.

**Comment by Toha1997** [comment]
I got the same error because I forgot to build from the source files in first place. Make sure to run the `yarn` and `make` commands and reload Grafana afterward. You have to install both yarn (https://classic.yarnpkg.com/en/docs/install/#windows-stable) and make (http://gnuwin32.sourceforge.net/packages/make.htm) beforehand.

**Comment by mimimath14** [comment]
Hi team,
I’m neewbe here and I never use a yarn and a make with windows 10 tool to resolve this issue:
Unexpected token '<' Evaluating http://127.0.0.1:8080/public/plugins/grafana-opcua-datasource/module.js Loading 

someone could explain me how to do it?

many thanks by advance
