### ISSUE TITLE
Whether to support reading opc ae (kepware)

### ISSUE THREAD

**Issue by mumugong** [grafana/opcua-datasource#8]
Whether to support reading opc ae, pay attention to the ae which is not opc ua. Such as kepware

**Comment by srclosson** [comment]
Hey @mumugong: Yes, great idea! I think my problem is finding a demo server that does this. Plus, grafana is changing the way AE works quite significantly. I sometimes feel like it's going to be better to wait a bit longer and implement properly, rather than implement it twice.

But if you could direct me towards a suitable OPC UA data source, I would very much appreciate it.

**Comment by srclosson** [comment]
Closing. Stale issue.
